name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.TOK }}
- name: Build the hello-docker Docker image
run: |
        docker build . --tag ghcr.io/ppoloskov/docker-sabnzdb:latest
       docker run ghcr.io/ppoloskov/docker-sabnzdb:latest
       docker push ghcr.io/ppoloskov/docker-sabnzdb:latest
